apiVersion: v1
kind: Service
metadata:
  name: VAR:INSTANCE_NAME
  labels:
    app: VAR:INSTANCE_NAME
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: VAR:INSTANCE_NAME

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: VAR:INSTANCE_NAME-deployment
  labels:
    app: VAR:INSTANCE_NAME
spec:
  replicas: VAR:REPLICAS_COUNT
  selector:
    matchLabels:
      app: VAR:INSTANCE_NAME
  template:
    metadata:
      labels:
        app: VAR:INSTANCE_NAME
    spec:
      volumes:
      - name: VAR:INSTANCE_NAME-letsencrypt
        persistentVolumeClaim:
          claimName: VAR:INSTANCE_NAME-letsencrypt
      - name: VAR:INSTANCE_NAME-cache
        emptyDir: {}
      containers:
      - name: VAR:INSTANCE_NAME
        command:
        - /bootstrap/entrypoint.sh
        image: wiilog/symfony:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/letsencrypt
          name: VAR:INSTANCE_NAME-letsencrypt
        - mountPath: /project/var/
          name: VAR:INSTANCE_NAME-cache
