apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: rabbitmq
data:
  enabled_plugins: |
    [rabbitmq_mqtt, rabbitmq_management, rabbitmq_prometheus].
  rabbitmq.conf: |
    queue_master_locator=min-masters
