apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiistock-VAR:INSTANCE_NAME-uploads-pv
  namespace: wiistock
spec:
  capacity:
    storage: VAR:UPLOADS_STORAGEGi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: wiistock-VAR:INSTANCE_NAME-nfs
  mountOptions:
    - tcp
    - nfsvers=3
  nfs:
    path: /zpool-127780/VAR:PARTITION_NAME
    server: 10.16.103.99

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: VAR:INSTANCE_NAME-uploads
  namespace: wiistock
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: wiistock-VAR:INSTANCE_NAME-nfs
  resources:
    requests:
      storage: VAR:UPLOADS_STORAGEGi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: VAR:INSTANCE_NAME
  namespace: wiistock
  labels:
    app: VAR:INSTANCE_NAME
    template: wiistock
spec:
  replicas: VAR:REPLICAS_COUNT
  selector:
    matchLabels:
      app: VAR:INSTANCE_NAME
  template:
    metadata:
      labels:
        app: VAR:INSTANCE_NAME
        template: wiistock
    spec:
      imagePullSecrets:
      - name: docker-token
      volumes:
      - name: project
        emptyDir: {}
      - name: uploads
        persistentVolumeClaim:
          claimName: VAR:INSTANCE_NAME-uploads
      - name: symfony-cache
        emptyDir: {}
      - name: cache
        persistentVolumeClaim:
          claimName: wiistock-cache
      initContainers:
      - name: cloner
        image: alpine/git
        args: ["clone", "--branch=VAR:BRANCH", "--single-branch", "https://github.com/benoitcostewiilog/WiiStock", "/project"]
        volumeMounts:
        - mountPath: /project
          name: project
      - name: initializer
        image: wiilog/symfony-initializer:latest
        command: ["/bootstrap/entrypoint.sh", "--with-migrations", "--with-fixtures", "--with-fos"]
        env:
        - name: DATABASE_HOST
          value: "VAR:DATABASE_HOST"
        - name: DATABASE_PORT
          value: "VAR:DATABASE_PORT"
        - name: DATABASE_USER
          value: "VAR:DATABASE_USER"
        - name: DATABASE_PASSWORD
          value: "VAR:DATABASE_PASS"
        - name: DATABASE_NAME
          value: "VAR:DATABASE_NAME"
        - name: DATABASE_URL
          value: "mysql://VAR:DATABASE_USER:VAR:DATABASE_PASS@VAR:DATABASE_HOST:VAR:DATABASE_PORT/VAR:DATABASE_NAME"
        - name: APP_ENV
          value: "VAR:ENV"
        - name: APP_LOCALE
          value: "VAR:CLIENT"
        - name: APP_CLIENT
          value: "VAR:CLIENT"
        - name: APP_URL
          value: "VAR:URL"
        - name: APP_DASHBOARD_TOKEN
          value: "VAR:DASHBOARD_TOKEN"
        volumeMounts:
        - mountPath: /project
          name: project
        - mountPath: /project/var
          name: symfony-cache
        - mountPath: /cache
          name: cache
      containers:
      - name: wiistock
        image: wiilog/symfony:latest
        command: ["/bootstrap/entrypoint.sh"]
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "mysql://VAR:DATABASE_USER:VAR:DATABASE_PASS@VAR:DATABASE_HOST:VAR:DATABASE_PORT/VAR:DATABASE_NAME"
        - name: APP_ENV
          value: "VAR:ENV"
        - name: APP_SECRET
          value: "VAR:SECRET"
        - name: APP_LOCALE
          value: "VAR:CLIENT"
        - name: APP_INSTANCE
          value: "VAR:INSTANCE_NAME"
        - name: APP_CLIENT
          value: "VAR:CLIENT"
        - name: APP_URL
          value: "VAR:URL"
        - name: APP_FORBIDDEN_PHONES
          value: "VAR:FORBIDDEN_PHONES"
        - name: APP_DASHBOARD_TOKEN
          value: "VAR:DASHBOARD_TOKEN"
        - name: APP_NO_MAIL
          value: "VAR:NO_MAIL"
        - name: CORS_ALLOW_ORIGIN
          value: "^https?://VAR:DOMAIN(:[0-9]+)?$"
        volumeMounts:
        - mountPath: /project
          name: project
        - mountPath: /project/public/uploads
          name: uploads
        - mountPath: /project/var
          name: symfony-cache

---
apiVersion: v1
kind: Service
metadata:
  name: VAR:INSTANCE_NAME
  namespace: wiistock
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: VAR:INSTANCE_NAME

---    
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: VAR:INSTANCE_NAME
  namespace: wiistock
  annotations:  
    cert-manager.io/issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"  
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
spec:
  tls:
  - hosts: ["VAR:DOMAIN"]
    secretName: VAR:INSTANCE_NAME-tls
  rules:
  - host: VAR:DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: VAR:INSTANCE_NAME
          servicePort: 80
