apiVersion: apps/v1
kind: Deployment
metadata:
  name: VAR:INSTANCE_NAME
  labels:
    app: VAR:INSTANCE_NAME
    template: symfony
spec:
  replicas: VAR:REPLICAS_COUNT
  selector:
    matchLabels:
      app: VAR:INSTANCE_NAME
  template:
    metadata:
      labels:
        app: VAR:INSTANCE_NAME
        template: symfony
    spec:
      volumes:
      - name: VAR:INSTANCE_NAME-project
        emptyDir: {}
      - name: VAR:INSTANCE_NAME-cache
        emptyDir: {}
      initContainers:
      - name: cloner
        image: alpine/git
        args: ["clone", "--branch=VAR:BRANCH", "--single-branch", "VAR:REPOSITORY", "/project"]
        volumeMounts:
        - mountPath: /project
          name: VAR:INSTANCE_NAME-project
      - name: initializer
        image: wiilog/symfony-initializer:latest
        command: ["/bootstrap/entrypoint.sh"]
        env:
        - name: DATABASE_HOST
          value: "VAR:DATABASE_HOST"
        - name: DATABASE_PORT
          value: "VAR:DATABASE_PORT"
        - name: DATABASE_USER
          value: "VAR:DATABASE_USER"
        - name: DATABASE_PASSWORD
          value: "VAR:DATABASE_PASS"
        - name: DATABASE_NAME
          value: "VAR:DATABASE_NAME"
        - name: DATABASE_URL
          value: "mysql://VAR:DATABASE_USER:VAR:DATABASE_PASS@VAR:DATABASE_HOST:VAR:DATABASE_PORT/VAR:DATABASE_NAME"
        - name: APP_ENV
          value: "VAR:ENV"
        VAR:NAME_1
        VAR:VALUE_1
        VAR:NAME_2
        VAR:VALUE_2
        VAR:NAME_3
        VAR:VALUE_3
        VAR:NAME_4
        VAR:VALUE_4
        VAR:NAME_5
        VAR:VALUE_5
        volumeMounts:
        - mountPath: /project
          name: VAR:INSTANCE_NAME-project
        - mountPath: /project/var
          name: VAR:INSTANCE_NAME-cache
      containers:
      - name: VAR:INSTANCE_NAME
        image: wiilog/symfony:latest
        command: ["/bootstrap/entrypoint.sh"]
        env:
        - name: DOMAIN
          value: "VAR:DOMAIN"
        - name: DATABASE_URL
          value: "mysql://VAR:DATABASE_USER:VAR:DATABASE_PASS@VAR:DATABASE_HOST:VAR:DATABASE_PORT/VAR:DATABASE_NAME"
        - name: APP_ENV
          value: "VAR:ENV"
        - name: APP_SECRET
          value: "VAR:SECRET"
        VAR:NAME_1
        VAR:VALUE_1
        VAR:NAME_2
        VAR:VALUE_2
        VAR:NAME_3
        VAR:VALUE_3
        VAR:NAME_4
        VAR:VALUE_4
        VAR:NAME_5
        VAR:VALUE_5
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /project
          name: VAR:INSTANCE_NAME-project
        - mountPath: /project/var
          name: VAR:INSTANCE_NAME-cache
